services:
  - name: taskmanager-backend
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "yourdomain.com,taskmanager.onrender.com"
      - key: REDIS_URL
        fromService:
          name: taskmanager-redis
          property: connectionString

  - name: taskmanager-db
    type: pserv
    env: postgres
    plan: free
    postgresMajorVersion: 15

  - name: taskmanager-redis
    type: redis
    plan: free

  - name: taskmanager-worker
    type: worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskmanager-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: taskmanager-redis
          property: connectionString
