# Generated by Django 5.1.6 on 2025-02-15 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_comment_text_comment_content_task_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('deadline', 'Deadline Reminder'), ('task_update', 'Task Update'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('project', 'user')},
        ),
    ]
